# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateTimeField(blank=True, null=True)),
                ('cust_number', models.CharField(max_length=10)),
                ('cust_name', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('fix', 'fix'), ('convert', 'convert'), ('lte', 'install/move'), ('htv', 'sat install')], max_length=10)),
                ('pair_day', models.NullBooleanField()),
                ('extra_charges', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
